// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "postgres://93b5bb65875634e7ac0559a28158ab30866ac2d241820499583b193ddd7e5bca:sk_Lxvli1XJWmeKLRmtQt_Hf@db.prisma.io:5432/postgres?sslmode=require",
  },
});
